### PR TITLE
Show estimated export size and display exportability warnings

### PR DESCRIPTION
**Pull request by Pytal**
### To Do

- [x] Try out combinations

#### Estimated size
image

#### Warning
image

### Requires

- [x] https://github.com/nextcloud/user_migration/pull/135

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
(did not test)

**Comment by Pytal** [comment]
After discusson with @come-nc estimated size has been changed from MiB with one significant digit to a whole number in MiB

Precision may be tweaked in a separate PR if needed

**Comment by Pytal** [comment]
After discussing with @come-nc the estimated size has been changed from MiB with one significant digit to a whole number in MiB

Precision may be tweaked in a separate PR if needed

**Pull request merged**
