### PR TITLE
Use exceptions instead of booleans

### PR DESCRIPTION
**Pull request by PVince81**
Adjust code according to the updated interfaces

- [x] REQUIRES: https://github.com/nextcloud/server/pull/31945

### CODE REVIEW

**Comment by PVince81** [comment]
static failure is because the master PR is not merged yet

**Review by Pytal — APPROVED** [review]

**Comment by PVince81** [comment]
master is merged, I've restarted the workflows

**Comment by PVince81** [comment]
boo, still failing. no idea... might need to retry the workflows later

**Comment by Pytal** [comment]
> boo, still failing. no idea... might need to retry the workflows later

Which one?

The Static analysis one would need to wait for next bump of `christophwurst/nextcloud` https://github.com/ChristophWurst/nextcloud_composer/commits/master which we can just ignore for now if urgent as server PR was merged

**Pull request merged**
