### PR TITLE
Drop account export and import

### PR DESCRIPTION
**Pull request by Pytal**
Drop account export and import in favour of https://github.com/nextcloud/server/pull/31382

### CODE REVIEW

**Comment by come-nc** [comment]
We should not treat it as a special case and just register it in core.

**Comment by Pytal** [comment]
> We should not treat it as a special case and just register it in core.

There are currently no RegistrationContext registrations being done in core so there was no clear place for this, @ChristophWurst any recommendation for where this should go?

**Comment by Pytal** [comment]
> > We should not treat it as a special case and just register it in core.
> 
> There are currently no RegistrationContext registrations being done in core so there was no clear place for this, @ChristophWurst any recommendation for where this should go?

@juliushaertl @nickvergessen any recommendations on making RegistrationContext registrations in core?

**Comment by juliushaertl** [comment]
Not fully sure I get the question correctly, let me know if not -  but in order to allow registration in the core RegistrationContext, you'd need to extend those parts in the server. https://github.com/nextcloud/server/pull/21850/files#diff-6f7fce46b3b19b872adcab3426e155b80766fd2b10feabc70ae29cbac2433a40 might be a good inspiration code wise.

**Comment by Pytal** [comment]
@juliushaertl yes the registration plumbing was done in https://github.com/nextcloud/server/pull/30901/files, by registrations in core I meant registering i.e. calling `registerUserMigrator()` in core and was wondering whether or not this would be doable within the existing bootstrapping code? as I looked through all the calls for the register methods of https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Bootstrap/IRegistrationContext.php and all registrations are done in an app rather than core

**Comment by Pytal** [comment]
@juliushaertl yes the registration plumbing was done in https://github.com/nextcloud/server/pull/30901/files

For clarification, by registrations in core I meant registering i.e. calling `registerUserMigrator()` in core and was wondering whether or not this would be doable within the existing bootstrapping code? as I looked through all the calls for the register methods of https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Bootstrap/RegistrationContext.php and https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Bootstrap/IRegistrationContext.php and all registrations are done in an app rather than core

**Comment by nickvergessen** [comment]
What would be the goal of this? Maybe you can do it in the settings app when it's about the user's settings or something? So there is always an app that does it?

On the other hand there is a never ending techdebt issue whether the core "app" should be turned into a full app.

**Comment by Pytal** [comment]
> What would be the goal of this? Maybe you can do it in the settings app when it's about the user's settings or something? So there is always an app that does it?
> 
> On the other hand there is a never ending techdebt issue whether the core "app" should be turned into a full app.

The goal is to put the migrators close to the classes they depend on i.e. AccountMigrator deals with account data which is handled by the classes in `lib/private/Accounts/` so placing the migrator there would be ideal

For the purposes of registration then yes I think the settings app would be the best app to put this into so will go with that, the techdebt looms large 💀

**Review by come-nc — APPROVED** [review]

**Pull request merged**
