### PR TITLE
Export and import files comments

### PR DESCRIPTION
**Pull request by come-nc**
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

### CODE REVIEW

**Comment by come-nc** [comment]
- [ ] Adapt to #22 (use original uid to detect own comments and assign them)
- [ ] Test deleted users comments and make sure imported comments appear the same way

**Comment by come-nc** [comment]
I tested and deleted users appear as «undefined» as well.

**Review by Pytal — CHANGES_REQUESTED** [review]
Did some testing and it seems that other users' comments become undefined on import and deleted users' comments are lost

Since comment actor matching is done by uid I think and another server could have a user with the same uid but be a different person then I'd say that addressing that is out of scope

This should however make it say something like "Deleted user" instead of undefined and not lose the comments of deleted users

**Comment by Pytal** [comment]
> Hum, regarding deleted users being shown as undefined, this is how it is done in core and should be handled in a separated issue there.

Opened an issue here https://github.com/nextcloud/server/issues/31654

**Comment by Pytal** [comment]
> Regarding having a special display for imported comments rather than showing them as from deleted users, I’m not sure if this is worth the hassle, I will have to look more into comments handling to see if it can cause trouble.

Yeah, let's see about that

**Comment by come-nc** [comment]
> > Regarding having a special display for imported comments rather than showing them as from deleted users, I’m not sure if this is worth the hassle, I will have to look more into comments handling to see if it can cause trouble.
> 
> Yeah, let's see about that

I think this should be kept as future scope, it would only change how we import things and not the export format so it can easily be changed later if we decide that imported comment users should have a special value for it. As deleted users are not nicely displayed currently this feels premature.

**Review by Pytal — APPROVED** [review]

**Pull request merged**
