### PR TITLE
Import account information

### PR DESCRIPTION
**Pull request by Pytal**
See title 👆

### CODE REVIEW

**Comment by come-nc** [comment]
@Pytal I think we should move this to a migrator as well to keep UserMigrationService clean.
Also, it’s always a problem to have relations to `OC\` namespace from an app. For applications that have their own repo they will have their migrator in there, but for applications which lives in core or even stuff which are not placed in an application like Account I’m not sure if they should stay here or go in server repository.

**Comment by come-nc** [comment]
We discussed this internally and decided going forward migrators should always be near classes they link against, unless they only link against OCP.
So this one would go in `server/lib/private/Accounts` I suppose.

**Comment by come-nc** [comment]
I have this difference after test script in database:
`\"email\":{\"value\":\"\",\"scope\":\"v2-federated\",\"verified\":\"0\"},` becomes `\"email\":{\"value\":\"\",\"scope\":\"v2-federated\",\"verified\":\"1\"},`

**Comment by Pytal** [comment]
> I have this difference after test script in database: `\"email\":{\"value\":\"\",\"scope\":\"v2-federated\",\"verified\":\"0\"},` becomes `\"email\":{\"value\":\"\",\"scope\":\"v2-federated\",\"verified\":\"1\"},`

The "1" indicates verification in progress and is working as intended https://github.com/nextcloud/server/blob/master/lib/private/Accounts/AccountManager.php#L408

**Comment by Pytal** [comment]
Superseded by https://github.com/nextcloud/server/pull/31382

**Pull request closed without merging**
