### PR TITLE
File picker filter by export extension

### PR DESCRIPTION
**Pull request by PVince81**
The file picker now only display files with the extension
".nextcloud_export"

- [x] REQUIRES: https://github.com/nextcloud/server/pull/31972
- [ ] TODO: raise ticket for clean approach with nextcloud-dialogs

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by Pytal — APPROVED** [review]

**Comment by PVince81** [comment]
@Pytal can you take over ? for the clean approach we need to go through nextcloud-dialogs and extend it there, which is a longer detour but will need to be done eventually

**Comment by Pytal** [comment]
@PVince81 I can take over this one, do you want to release this now and https://github.com/nextcloud/nextcloud-dialogs for 0.2?

**Comment by Pytal** [comment]
Issue opened to add filter to https://github.com/nextcloud/nextcloud-dialogs package https://github.com/nextcloud/nextcloud-dialogs/issues/560

**Comment by Pytal** [comment]
Everything for [milestone 1.0](https://github.com/nextcloud/user_migration/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+milestone%3A1.0) is in and released in v1.0.1-beta.2 https://github.com/nextcloud/user_migration/pull/119

**Pull request merged**
