### PR TITLE
Upgrade to @nextcloud/vue v7 and cleanup

### PR DESCRIPTION
**Pull request by Pytal**
For https://github.com/nextcloud/user_migration/issues/235

### CODE REVIEW

**Comment by Pytal** [comment]
`main` is on the 1.3 milestone, the backport will be 1.2

**Review by come-nc — COMMENTED** [review]
Would be nice if @artonge can review this, too much frontend for me to do a useful review.

**Review by artonge — APPROVED** [review]
Looks good

**Pull request merged**
