### PR TITLE
[stable24] Update nextcloud/ocp dependency

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency

### CODE REVIEW

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
I believe the failing Postgres CI is already known @come-nc? Fine to merge?

**Comment by come-nc** [comment]
> I believe the failing Postgres CI is already known @come-nc? Fine to merge?

Should be fixed by https://github.com/nextcloud/user_migration/pull/305

**Pull request merged**
